### ISSUE TITLE
'CF_EventHandler' invoke error

### ISSUE THREAD

**Issue by VoxelVirus** [Arkensor/DayZ-CommunityFramework#141] opened 2023-02-16 19:55 UTC
Ever since the 1.20 update I've been getting this error upon logging in. I've already tried the fix of deleting the dta folder and .exe files, then verifying my install via steam. Still getting the same error after.

[crash_2023-02-16_14-47-43.log](https://github.com/Arkensor/DayZ-CommunityFramework/files/10760242/crash_2023-02-16_14-47-43.log)

**Comment by Arkensor** [comment] 2023-02-18 10:27
Hello, we are aware of this error but not for logging in? We currently reproduced it when you exit a server. When exactly does it happen to you? Can you reproduce it and check the log after each step to see when it appears? So we know if it happens on reconnect or on the first disconnect or what ever?

**Comment by VoxelVirus** [comment] 2023-02-21 19:40
I can no longer reproduce the crash, but I was getting it very consistently on each login attempt every time I tried to join the server. During the few instances where I was able to successfully connect, I would sometimes randomly just crash to desktop with the error being in the logs.

I suspect other mods were causing the crash, since there have been updates since then and the crashing has stopped completely.

Here are some other logs that include the CF_EventHandler error.

[crash_2023-02-19_14-57-29.log](https://github.com/Arkensor/DayZ-CommunityFramework/files/10796972/crash_2023-02-19_14-57-29.log)
[crash_2023-02-18_17-39-12.log](https://github.com/Arkensor/DayZ-CommunityFramework/files/10796973/crash_2023-02-18_17-39-12.log)

**Comment by Arkensor** [comment] 2023-02-26 11:35
@VoxelVirus it would help if you only attempted it once, so the crash is isolated. Your log is full of errors from base game and other mods too.

**Comment by AuroraCrimsonRose** [comment] 2023-05-02 12:26
H
[crash_2023-05-02_07-52-56.log](https://github.com/Arkensor/DayZ-CommunityFramework/files/11373017/crash_2023-05-02_07-52-56.log)
aving a Similar issue when joining a server, causes CTD.

**Comment by AuroraCrimsonRose** [comment] 2023-05-02 12:27
Its Repeatable consistent and repeatable.

**Comment by AuroraCrimsonRose** [comment] 2023-05-02 13:39
And another from another machine as well. 
[crash_2023-05-02_07-23-48.log](https://github.com/Arkensor/DayZ-CommunityFramework/files/11373766/crash_2023-05-02_07-23-48.log)

**Comment by AuroraCrimsonRose** [comment] 2023-05-02 15:34
Seems to do this on dying and trying to respawn? it crashes to desktop and then you have to clear everything in %appdata% or it'll crash again.

**Comment by Arkensor** [comment] 2023-05-03 16:16
Hey, thanks for the info, I will investigate it as soon as I can

**Comment by EzHeisenberg** [comment] 2023-07-14 21:51
Hello, any fix for this error ? My friend try to join our server, but he had CF_EventHandler in crash log, but on other servers it manages to join while they also use the CF mod

**Closed as completed** 2023-07-22 09:30 UTC
Labels: bug

**Comment by LarryCSS** [comment] 2023-12-10 05:12
Boa-noite estou tendo esse erro e várias pessoas também não consegue jogar
devido a esse erro não conectar de primeira nem de segunda para conseguir conectar tem 
que fecha a Steam e abri novamente muito trabalho para conseguir conectar.

![image](https://github.com/Arkensor/DayZ-CommunityFramework/assets/153412313/77867684-efcd-4fa7-9cc3-262fc4cdf1f2)

**Comment by LarryCSS** [comment] 2023-12-10 05:15
Good evening, I'm having this error and several people can't play either.
due to this error not connecting for the first or second time to be able to connect,
You need to relog Steam again to be able to connect.

10.12 2023 01:20:21
NULL pointer to instance
Class:      'CF_EventHandler'
Function: 'Invoke'
Stack trace:
JM/CF/Scripts/2_GameLib/communityframework\eventhandler\cf_eventhandler.c:79
JM/CF/Scripts/5_Mission/communityframework\lifecycleevents\missionbase.c:9
scripts/5_Mission/somemission.c:25

**Comment by LarryCSS** [comment] 2023-12-10 05:34
This error happened again after last hotfix dayz 1.23

**Comment by Arkensor** [comment] 2023-12-15 12:08
Hello @LarryCSS,

the error message indicates that you might be using an outdated version of the mod. Please use the official DayZ launcher to rightclick -> repair the mod.
